// `.env.ts` is generated by the `npm run env` command
import env from './.env';

// This file is used for aws deployment. check package.json and angular-cli.json for further information

function loadJSON(filePath: string) {
  const json = loadTextFileAjaxSync(filePath, 'application/json');
  return JSON.parse(json);
}

function loadTextFileAjaxSync(filePath: string, mimeType: string) {
  const xmlhttp = new XMLHttpRequest();
  xmlhttp.open('GET', filePath, false);
  if (mimeType != null) {
    if (xmlhttp.overrideMimeType) {
      xmlhttp.overrideMimeType(mimeType);
    }
  }
  xmlhttp.send();
  if (xmlhttp.status == 200) {
    return xmlhttp.responseText;
  } else {
    return null;
  }
}

export const environment = loadJSON('/assets/config.json');
